version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: devops_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: devops_frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules